# golangci-lint configuration for Kratos project
# Compatible with golangci-lint v2.x
# See: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - wireinject

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: QuotaLane

linters-settings:

  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G104
      - G304

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: wire_gen\.go
      linters:
        - all

    - path: (third_party|api)/.*\.pb\.go
      linters:
        - all
