# golangci-lint configuration for Kratos project
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - wireinject

linters:
  enable:
    - gofmt       # Checks whether code was gofmt-ed
    - goimports   # Check import statements are formatted
    - govet       # Vet examines Go source code and reports suspicious constructs
    - errcheck    # Checks for unchecked errors
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unused      # Checks Go code for unused constants, variables, functions and types
    - gosimple    # Linter for Go source code that specializes in simplifying code
    - ineffassign # Detects when assignments to existing variables are not used
    - typecheck   # Like the front-end of a Go compiler, parses and type-checks Go code
    - goconst     # Finds repeated strings that could be replaced by a constant
    - misspell    # Finds commonly misspelled English words in comments
    - revive      # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert   # Remove unnecessary type conversions
    - gosec       # Inspects source code for security problems

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: QuotaLane

  govet:
    enable-all: true

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path provided as taint input (too many false positives)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Exclude wire_gen.go (auto-generated)
    - path: wire_gen\.go
      linters:
        - all

    # Exclude third_party and api proto generated files
    - path: (third_party|api)/.*\.pb\.go
      linters:
        - all
