# golangci-lint configuration for Kratos project
# Compatible with golangci-lint v1.64.x (used in CI)
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - wireinject

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gosec
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: QuotaLane

  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: true  # Disabled to avoid type name stuttering warnings (e.g., oauth.OAuthProvider)
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G104  # Audit errors not checked (handled by errcheck linter)
      - G304  # File path provided as taint input (false positives in tests)
      - G101  # Hardcoded credentials (false positives for OAuth endpoint URLs)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: wire_gen\.go
      linters:
        - all

    - path: (third_party|api)/.*\.pb\.go
      linters:
        - all
